### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by mb-wali** [fair-data-austria/invenio-rdm-pure#10]
This file runs in a separate environment rather than the module itself.
we need to refactor the ```cli.py``` file for this module. and use the [Flask.commands](https://flask.palletsprojects.com/en/1.1.x/cli/).

_Originally posted by @mb-wali in https://github.com/tu-graz-library/invenio-rdm-pure/pull/9#r514180298_

# Roadmap

  - [ ] replace docopt with click
  - [ ] move the run files somewhere more meaningful (still under discussion)
  - [ ] make it possible to run it in on celery/cronjob (hopefully [3] @with_appcontext is enough for that)

# References
  - [1] https://github.com/inveniosoftware/invenio-rdm-records/blob/fe79d34f96e769000af81d7f9b1dce55dd18ff22/invenio_rdm_records/cli.py#L174
  - [2] https://github.com/inveniosoftware/invenio-cli/blob/44035e318ebafae45e1979dae1f2799f4a055923/invenio_cli/helpers/commands.py#L228
  - [3] https://github.com/inveniosoftware/invenio-rdm-records/blob/fe79d34f96e769000af81d7f9b1dce55dd18ff22/invenio_rdm_records/cli.py#L17

**Comment by utnapischtim** [comment]
it is true that we have to refactor the cli:

  - [ ] replace docopt with click
  - [ ] move the run files somewhere more meaningful (still under discussion)
  - [ ] make it possible to run it in on celery/cronjob (hopefully [3] @with_appcontext is enough for that)

references:
  - [1] https://github.com/inveniosoftware/invenio-rdm-records/blob/fe79d34f96e769000af81d7f9b1dce55dd18ff22/invenio_rdm_records/cli.py#L174
  - [2] https://github.com/inveniosoftware/invenio-cli/blob/44035e318ebafae45e1979dae1f2799f4a055923/invenio_cli/helpers/commands.py#L228
  - [3] https://github.com/inveniosoftware/invenio-rdm-records/blob/fe79d34f96e769000af81d7f9b1dce55dd18ff22/invenio_rdm_records/cli.py#L17
